<?php

use App\Controllers\AdminController;
use App\Controllers\AiAssistantController;
use App\Controllers\AuctionController;
use App\Controllers\AuthController;
use App\Controllers\CheckoutController;
use App\Controllers\CatalogController;
use App\Controllers\CartController;
use App\Controllers\ChatController;
use App\Controllers\FavoriteController;
use App\Controllers\HomeController;
use App\Controllers\OrderController;
use App\Controllers\PaymentController;
use App\Controllers\ProductController;
use App\Controllers\ProfileController;
use App\Controllers\StoryController;
use App\Controllers\StreamController;
use App\Controllers\SupportController;
use App\Controllers\WalletController;
use App\Core\Router;

$router = new Router();

$router->get('/', [HomeController::class, 'index']);
$router->get('/about', [HomeController::class, 'about']);
$router->get('/about/document/{slug}', [HomeController::class, 'aboutDocument']);
$router->get('/offer', [HomeController::class, 'offer']);
$router->get('/privacy', [HomeController::class, 'privacy']);
$router->get('/data-policy', [HomeController::class, 'dataPolicy']);
$router->get('/catalog/{section}', [CatalogController::class, 'show']);
$router->get('/auctions', [AuctionController::class, 'index']);
$router->post('/auctions/{id}/bid', [AuctionController::class, 'bid']);
$router->get('/product/{id}', [ProductController::class, 'show']);
$router->get('/checkout/success/{id}', [CheckoutController::class, 'success']);
$router->get('/checkout/cart', [CheckoutController::class, 'cartShow']);
$router->post('/checkout/cart/pay', [CheckoutController::class, 'cartPay']);
$router->get('/checkout/{id}', [CheckoutController::class, 'show']);
$router->post('/checkout/{id}/pay', [CheckoutController::class, 'pay']);
$router->post('/payments/freedompay/result', [PaymentController::class, 'freedomPayResult']);
$router->get('/payments/freedompay/success', [PaymentController::class, 'freedomPaySuccess']);
$router->get('/payments/freedompay/failure', [PaymentController::class, 'freedomPayFailure']);
$router->get('/orders', [OrderController::class, 'index']);
$router->get('/orders/{id}', [OrderController::class, 'show']);
$router->post('/orders/{id}/ship', [OrderController::class, 'ship']);
$router->post('/orders/{id}/delivered', [OrderController::class, 'delivered']);
$router->post('/orders/{id}/confirm', [OrderController::class, 'confirm']);
$router->post('/orders/{id}/cancel', [OrderController::class, 'cancel']);
$router->post('/orders/{id}/dispute', [OrderController::class, 'dispute']);
$router->post('/orders/{id}/return-ship', [OrderController::class, 'returnShip']);
$router->post('/orders/{id}/return-received', [OrderController::class, 'returnReceived']);
$router->post('/orders/{id}/approve-return', [OrderController::class, 'approveReturn']);
$router->post('/orders/{id}/reject-dispute', [OrderController::class, 'rejectDispute']);
$router->post('/orders/{id}/review', [OrderController::class, 'review']);
$router->get('/wallet', [WalletController::class, 'index']);
$router->post('/wallet/deposit', [WalletController::class, 'deposit']);
$router->post('/wallet/withdraw', [WalletController::class, 'withdraw']);
$router->get('/chat', [ChatController::class, 'index']);
$router->get('/chat/start', [ChatController::class, 'start']);
$router->post('/chat/start', [ChatController::class, 'start']);
$router->get('/chat/{id}/thread', [ChatController::class, 'thread']);
$router->get('/chat/{id}/poll', [ChatController::class, 'poll']);
$router->post('/chat/{id}/send', [ChatController::class, 'send']);
$router->get('/chat/{id}', [ChatController::class, 'show']);
$router->get('/support', [SupportController::class, 'index']);
$router->get('/support/new', [SupportController::class, 'createForm']);
$router->post('/support', [SupportController::class, 'store']);
$router->get('/support/{id}', [SupportController::class, 'show']);
$router->post('/support/{id}/reply', [SupportController::class, 'reply']);
$router->post('/favorites/{id}/toggle', [FavoriteController::class, 'toggle']);
$router->get('/cart', [CartController::class, 'index']);
$router->post('/cart/clear', [CartController::class, 'clear']);
$router->post('/cart/{id}/toggle', [CartController::class, 'toggle']);
$router->post('/cart/{id}/remove', [CartController::class, 'remove']);
$router->post('/ai/chat', [AiAssistantController::class, 'chat']);
$router->get('/ai/chat/messages', [AiAssistantController::class, 'messages']);
$router->post('/ai/chat/feedback', [AiAssistantController::class, 'feedback']);

$router->get('/login', [AuthController::class, 'loginForm']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/login/2fa', [AuthController::class, 'twoFactorForm']);
$router->post('/login/2fa', [AuthController::class, 'twoFactorVerify']);
$router->get('/register', [AuthController::class, 'registerForm']);
$router->post('/register', [AuthController::class, 'register']);
$router->get('/forgot-password', [AuthController::class, 'forgotPasswordForm']);
$router->post('/forgot-password', [AuthController::class, 'forgotPassword']);
$router->get('/reset-password/{token}', [AuthController::class, 'resetPasswordForm']);
$router->post('/reset-password/{token}', [AuthController::class, 'resetPassword']);
$router->get('/auth/google', [AuthController::class, 'googleRedirect']);
$router->get('/auth/google/callback', [AuthController::class, 'googleCallback']);
$router->post('/logout', [AuthController::class, 'logout']);

$router->get('/profile', [ProfileController::class, 'index']);
$router->post('/profile/store', [ProfileController::class, 'store']);
$router->post('/profile/lots/{id}/update', [ProfileController::class, 'updateLot']);
$router->post('/profile/lots/{id}/delete', [ProfileController::class, 'deleteLot']);
$router->post('/profile/avatar', [ProfileController::class, 'avatar']);
$router->post('/profile/personal', [ProfileController::class, 'updatePersonal']);
$router->post('/profile/bio', [ProfileController::class, 'updateBio']);
$router->post('/profile/password', [ProfileController::class, 'updatePassword']);
$router->post('/profile/2fa/setup', [ProfileController::class, 'twoFactorSetup']);
$router->post('/profile/2fa/confirm', [ProfileController::class, 'twoFactorConfirm']);
$router->post('/profile/2fa/disable', [ProfileController::class, 'twoFactorDisable']);
$router->post('/profile/delete', [ProfileController::class, 'deleteAccount']);
$router->post('/notifications/clear', [ProfileController::class, 'clearNotifications']);
$router->get('/orders/{id}/evidence/{file}', [OrderController::class, 'evidence']);

$router->post('/stories', [StoryController::class, 'store']);
$router->post('/stories/{id}/delete', [StoryController::class, 'delete']);

$router->post('/streams/live/start', [StreamController::class, 'startLive']);
$router->post('/streams/live/heartbeat', [StreamController::class, 'heartbeat']);
$router->post('/streams/live/end', [StreamController::class, 'endLive']);
$router->post('/streams/live/signal', [StreamController::class, 'signal']);
$router->get('/streams/live/signal/poll', [StreamController::class, 'signalPoll']);
$router->post('/streams/{id}/delete', [StreamController::class, 'delete']);

$router->get('/admin', [AdminController::class, 'index']);
$router->get('/admin/logs', [AdminController::class, 'logs']);
$router->get('/admin/tickets', [AdminController::class, 'tickets']);
$router->get('/admin/tickets/{id}', [AdminController::class, 'ticketShow']);
$router->post('/admin/tickets/{id}/reply', [AdminController::class, 'ticketReply']);
$router->post('/admin/tickets/{id}/close', [AdminController::class, 'ticketClose']);
$router->post('/admin/tickets/{id}/reopen', [AdminController::class, 'ticketReopen']);
$router->get('/admin/ai-chats', [AdminController::class, 'aiChats']);
$router->get('/admin/ai-chats/{id}', [AdminController::class, 'aiChatShow']);
$router->post('/admin/ai-chats/{id}/reply', [AdminController::class, 'aiChatReply']);
$router->post('/admin/ai-chats/{id}/close', [AdminController::class, 'aiChatClose']);
$router->get('/admin/ai-export-dataset', [AdminController::class, 'aiExportDataset']);
$router->get('/admin/users', [AdminController::class, 'users']);
$router->get('/admin/users/{id}', [AdminController::class, 'userShow']);
$router->post('/admin/users', [AdminController::class, 'userCreate']);
$router->post('/admin/users/{id}/role', [AdminController::class, 'userUpdateRole']);
$router->post('/admin/users/{id}/permissions', [AdminController::class, 'userUpdatePermissions']);
$router->post('/admin/users/{id}/site-access', [AdminController::class, 'userToggleSiteAccess']);
$router->post('/admin/users/{id}/delete', [AdminController::class, 'userDelete']);
$router->post('/admin/delete/{id}', [AdminController::class, 'delete']);
$router->post('/admin/toggle/{id}', [AdminController::class, 'toggleStatus']);
$router->post('/admin/site-status', [AdminController::class, 'toggleSiteStatus']);

return $router;
